const list = [
  "Civil Engineering",
  "Bio Medical Engineering",
  "Building Engineering and Construction Technology",
  "Interior Design",
  "Planning",
  "Construction Technology & MGT",
  "MCA(Integrated)",
  "Mining Engineering",
  "VLSI Design",
  "Computer Science(Software Engineering)",
  "Computer Science and Engineering",
  "Computer Science and Information Technology",
  "Computer Science",
  "Information Technology",
  "MCA",
  "Computer Engineering",
  "CAD CAM",
  "Mechanical(CAD)",
  "Advance Computer Aided Design",
  "Computer (Distributed System)",
  "Electrical Engineering",
  "Electrical & Electronics Engineering",
  "Instrumentation and Control Engineering",
  "Electrical & Computer Engg.",
  "Electrical And Electronics(Power Electronics)",
  "Remote Sensing & GIS",
  "Computer Integrated Manufacturing",
  "Digital Communications",
  "Electrical Engineering(Electrical Power And Energy Systems)",
  "Electrical(Power System)",
  "Electronics Engineering",
  "Electronics and Communication Engineering",
  "Electronics and Instrumentation Engineering",
  "Electronics and Telecommunication Engineering",
  "Electronics, Instrumentation and Control Engineering",
  "Applied Electronics and Instrumentation Engineering",
  "Bachelor of Design",
  "Electronics Design And Technology",
  "Electronics (Control Systems)",
  "MBA(Integrated)",
  "Mechanical Engineering",
  "Manufacturing Technology",
  "Manufacturing Science & Technology",
  "Mechanical and Industrial Engineering",
  "Production Engineering",
  "Industrial Production Engineering",
  "Production and Industrial Engineering",
  "Automobile Engineering",
  "Aeronautical Engineering",
  "Petroleum Engineering",
  "Bachelor of Pharmacy",
  "Chemical Engineering",
  "Chemical & Bio Engg.",
  "Chemical & Alcohol Technology",
  "Biotechnology",
  "Bio Chemical Engineering",
  "Pharmaceutics",
  "Pharmceutical Chemistry",
  "Pharmacogonosy",
  "Marine Engineering",
  "Textile Chemistry",
  "Textile Technology",
  "Man Made Fibre Technology",
  "Textile Engineering",
  "Carpet & Textile Technology",
  "BFAD",
  "Bachelor of Fine Art(BFA)",
  "Computer science and engineering with specialization in cyber security/ ICT",
  "Electronics(Microwave Enginnering)",
  "Thermal Engineering",
  "MBA",
  "MBA in Tourism Management",
  "MBA Rural Development",
  "Structural Engineering",
  "BHMCT",
  "Automation and Robotics",
  "Power Electronics And Drives",
  "Power Systems",
  "Machine Design",
  "Electronic And Computer Engineering",
  "Agricultural Engineering",
  "Architecture",
  "Food Technology",
  "PHARMACEUTICAL REGULATORY AFFAIRS",
  "Chemical Technology - Oil Technology",
  "Master of Architecutre",
  "Leather Technology",
  "Plastic Engineering",
  "Electrical Drive and Control",
  "Information & Communication Technology",
  "MBA(international Business",
  "Quality Assurance",
  "Computer Network Engg",
  "Masters of Applied Mangement",
  "MCA Dual Degree",
  "Mechatronics",
  "Nanotechnology",
  "Environmental Engineering",
  "Pharmacology",
  "PHARMACEUTICAL QUALITY ASSURANCE",
  "Automotive Manufacturing Technology",
  "Automobile Servicing",
  "Production Technology",
  "Industrial Tool Manufacturing (ITM)",
  "Refrigeration and Air Conditioning",
  "Softwaree Development",
  "Graphics & Mutimedia",
  "BFSI",
  "Travel & Tourism",
  "Food Processing",
  "Electronic Manufacturing Servicing",
  "Medical Imaging Technology",
  "Printing & Packing Technology",
  "Communication Engineering",
  "Mobile Communication",
  "Artificial Intelligence",
  "Energy Science & Technology",
  "Fashion Design",
  "Microelectronics Engineering",
  "Pharmaceutical Analysis",
  "Pharmaceutical Analysis And Quality Assurance",
  "M.Pharma.",
  "Geotechnical & Geoenvironmental Engineering",
  "M.Design.",
  "Advance Electronics & Communication Engineering",
  "Chemical Technology",
  "Communication & Information System",
  "Computer Hardware & Networking",
  "Computer Engineering And Information Technology",
  "Urban and Regional Planning",
  "Computer Science & Technology",
  "Construction Technology & Management",
  "Digital Electronics & Commuincation Engineering",
  "Drug Regulatory",
  "Electronics Circutis & System Design",
  "Enviourmentaion Technology",
  "Machine Design & Industrial System Engineering",
  "Machine Design & Robotics",
  "Manufacturing System",
  "Mechanical & Manufacturing",
  "Mechanical Engineering Design",
  "BBA",
  "Pharmaceutical",
  "Telecomm Engineering",
  "VLSI & Embed System",
  "Pharmaceutical Marketing MGT.",
  "Ceramic Technology",
  "Chemical Technology - Paint Technology",
  "Manufacturing Science and Automation",
];

module.exports = list;
